### ISSUE TITLE
Feature d'inversion des couleurs

### ISSUE THREAD

**Issue by LouisLaiolo** [LouisLaiolo/Da-Gam#5]
On veut ajouter une nouvelle mécanique de jeu : l'inversion des couleurs.

Quand le joueur active un trigger A (disons par exemple, un levier), toutes les zones blanches de l'environnement sur une zone fermée et clairement définie deviendront noires. En parallèle, toutes les zones initialement noires situées dans cette même zone deviendront blanches. Les objets rouges ne changent pas.

Au bout d'un timer de X secondes, toutes les couleurs reprennent leur valeur initial.

**Exemple : Vous entrez dans une maison, au sein d'un niveau. Le plafond de cette maison est noir, les murs blancs, et le sol rouge. Vous activez un levier, situé dans cette même maison.**

Le plafond deviendra blanc, les murs noirs, le sol reste rouge. Le joueur inverse également sa couleur initial. Au bout de 5 secondes, tout redevient normal. Seule la maison était influencée par le trigger.

**Comment by YannickCardini** [comment]
Est ce qu'il faut reinitialiser l'animation du levier ?  Par exmple quand j'enclenche le levier il est abaissé, il faut le remettre à la position haute après 5 secondes pour pouvoir le reactiver ?

**Comment by LouisLaiolo** [comment]
J'ai oublié de le préciser, mais oui. Le joueur peut enclencher ce système quand bon lui semble. Du coup :

1. Le joueur abaisse le levier/trigger
2. Tant que le levier est baissé, le trigger ne peut pas être relancé
3. Event lié au trigger pendant X sec sur une zone définie
4. Event terminé au bout des X sec, tout reprend son état initial, y compris le levier

Une rapide explication de l'environnement pour t'aider : Tous les objets ont une variable d'instance "collisionGroup" qui permet d'identifier leur couleur (2 = blanc, 4= noir, 6 = rouge). Il en va de même pour le joueur (ce dernier peut alterner la valeur de cette variable grâce aux clics de la souris).

Aussi, tous les objets susceptibles d'être inversés ont une animation "inverse" qui correspond à leur aspect dans l'autre couleur. Ton objectif est de modifier les variables d'instances concernées pendant un temps défini, dans une zone définie, et de mettre à jour l'animation adéquate. Ensuite, tout revient à la normal.

**Comment by YannickCardini** [comment]
Ça ne marche pas comme ca, les collisions sont fixés à "enabled" and "disabled" en fonction de la valeur "player.collisiongroup". Je vais réfléchir à une autre solution

**Comment by YannickCardini** [comment]
Done, issue terminé j'ai merge avec la branche master tu me diras ce que tu en penses
